[package]
name = "rust-db-admin"
version = "0.1.0"
authors = ["rosarp <rohi7ns@gmail.com>"]

[dependencies]
rocket = { version = "0.3.6", features = ["tls"] }
rocket_codegen = "0.3.6"
diesel = "1.1.1"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
